version: "3.8"
services:
  proxy:
      image: nginx:latest
      ports:
        - 8080:80
      volumes:
        - ./nginx:/etc/nginx:ro
      environment:
        NGINX_PORT: 80
  srdecny:
    container_name: srdecny.php
    image: php:7.4-apache
    volumes:
      - ./srdecny:/var/www/html